/**
 * Brazilian-Portuguese UI copy. Components reference these keys; no hardcoded
 * pt-BR strings live in components (KTD11). Entity units extend their sections.
 */
export const labels = {
  app: {
    name: "SGPPF",
    full: "Sistema de Gestão de Projetos, Publicações e Financiamentos",
  },
  nav: {
    dashboard: "Painel",
    researchers: "Pesquisadores",
    projects: "Projetos",
    publications: "Publicações",
    advisings: "Orientações",
    admin: "Administração",
    signOut: "Sair",
  },
  shell: {
    institution: "Instituto Mauá de Tecnologia",
    management: "Gestão acadêmica",
    account: "Conta institucional",
    openNavigation: "Abrir navegação",
    closeNavigation: "Fechar navegação",
    collapseNavigation: "Recolher navegação",
    expandNavigation: "Expandir navegação",
    descriptions: {
      dashboard: "Visão geral",
      researchers: "Perfis acadêmicos",
      projects: "Pesquisa e fomento",
      publications: "Produção científica",
      advisings: "Formação acadêmica",
      admin: "Acessos e papéis",
    },
  },
  roles: {
    admin: "Administrador",
    researcher: "Pesquisador",
    consultant: "Consultor",
  },
  researcher: {
    name: "Nome",
    email: "E-mail",
    department: "Departamento",
    unit: "Unidade",
    position: "Cargo",
    area: "Área de atuação",
    role: "Papel",
    orcid: "ORCID",
    lattes: "Currículo Lattes (URL)",
    scholar: "Google Scholar ID",
    researchGate: "ResearchGate ID",
    employmentType: "Vínculo",
    affiliationDate: "Data de admissão",
    inactive: "Inativo",
  },
  publication: {
    title: "Título",
    doi: "DOI",
    type: "Tipo",
    year: "Ano",
    venue: "Veículo (periódico/evento)",
    issn: "ISSN",
    url: "URL",
    qualis: "Qualis",
    impactFactor: "Fator de impacto",
    citationCount: "Citações",
    area: "Área de conhecimento",
    authors: "Autores",
    claimAuthorship: "Sou autor(a)",
    corresponding: "correspondente",
    noAuthors: "Nenhum autor vinculado",
    doiPreviewHint: "Confira os dados importados do Crossref antes de salvar.",
    doiExists: "Esta publicação já existe.",
    viewExisting: "Ver publicação",
    doiInvalid: "DOI inválido.",
    doiNotFound: "DOI não encontrado no Crossref.",
    doiFailed: "Falha ao consultar o Crossref. Tente novamente ou insira manualmente.",
    importByDoiTitle: "Importar por DOI",
    manualEntry: "Ou cadastre manualmente",
  },
  publicationTypes: {
    article: "Artigo",
    conference_paper: "Trabalho em congresso",
    book: "Livro",
    book_chapter: "Capítulo de livro",
    technical_report: "Relatório técnico",
    patent: "Patente",
  },
  project: {
    title: "Título",
    code: "Código",
    description: "Descrição",
    modality: "Modalidade",
    status: "Situação",
    lead: "Responsável",
    members: "Equipe envolvida",
    startDate: "Início",
    endDate: "Término",
    funding: "Financiamentos",
  },
  projectStatus: {
    planned: "Planejado",
    in_progress: "Em andamento",
    completed: "Concluído",
    cancelled: "Cancelado",
  },
  funding: {
    agency: "Agência",
    modality: "Modalidade",
    approved: "Valor aprovado",
    received: "Valor recebido",
    pending: "Saldo",
    status: "Situação",
    startDate: "Início",
    endDate: "Término",
    addTitle: "Adicionar financiamento",
  },
  fundingStatus: {
    approved: "Aprovado",
    in_execution: "Em execução",
    completed: "Encerrado",
    cancelled: "Cancelado",
  },
  advising: {
    student: "Aluno(a)",
    level: "Nível",
    workTitle: "Título do trabalho",
    status: "Situação",
    advisor: "Orientador(a)",
    coAdvisor: "Coorientador(a)",
    project: "Projeto vinculado",
    scholarshipAgency: "Agência da bolsa",
    startDate: "Início",
    endDate: "Conclusão",
    none: "—",
  },
  advisingLevel: {
    scientific_initiation: "Iniciação Científica",
    undergraduate_thesis: "TCC",
    masters: "Mestrado",
    doctorate: "Doutorado",
    postdoc: "Pós-doutorado",
  },
  advisingStatus: {
    in_progress: "Em andamento",
    completed: "Concluída",
    cancelled: "Cancelada",
  },
  admin: {
    status: "Situação",
    active: "Ativo",
  },
  actions: {
    create: "Novo",
    edit: "Editar",
    delete: "Excluir",
    save: "Salvar",
    cancel: "Cancelar",
    confirm: "Confirmar",
    search: "Buscar",
    exportCsv: "Exportar CSV",
    importDoi: "Importar por DOI",
  },
  table: {
    previous: "Anterior",
    next: "Próxima",
    records: "registros",
    recordsOne: "registro",
  },
  auth: {
    signIn: "Entrar",
    signUp: "Criar conta",
    email: "E-mail institucional",
    password: "Senha",
    fullName: "Nome completo",
    noAccount: "Não tem conta?",
    hasAccount: "Já tem conta?",
    signInWithMicrosoft: "Entrar com Microsoft", // shown once Azure provider is enabled
    checkEmail:
      "Conta criada. Confirme seu e-mail institucional para entrar — verifique sua caixa de entrada.",
  },
  errors: {
    required: "Campo obrigatório",
    invalidEmail: "E-mail inválido",
    invalidCredentials: "E-mail ou senha inválidos",
    duplicate: "Esse valor já está em uso",
    notMauaEmail: "Use seu e-mail institucional da Mauá",
    unauthorized: "Você não tem permissão para esta ação",
    generic: "Algo deu errado. Tente novamente.",
  },
  dialogs: {
    confirmDelete: {
      title: "Confirmar exclusão",
      description: "Esta ação não pode ser desfeita.",
      confirm: "Excluir",
      cancel: "Cancelar",
    },
  },
  empty: {
    researchers: {
      title: "Nenhum pesquisador cadastrado",
      description: "Os pesquisadores aparecerão aqui assim que forem adicionados.",
    },
    projects: {
      title: "Nenhum projeto cadastrado",
      description: "Crie um projeto para começar a registrar financiamentos e publicações.",
    },
    publications: {
      title: "Nenhuma publicação registrada",
      description: "Importe por DOI ou registre manualmente.",
    },
    advisings: {
      title: "Nenhuma orientação registrada",
      description: "As orientações aparecerão aqui assim que forem adicionadas.",
    },
    funding: {
      title: "Nenhum financiamento registrado",
      description: "Adicione um contrato de financiamento a este projeto.",
    },
  },
  dashboard: {
    title: "Painel",
    eyebrow: "Visão institucional",
    welcome: "Acompanhe a atividade acadêmica da Mauá",
    description:
      "Indicadores consolidados para uma leitura rápida da produção científica, formação e captação de recursos.",
    overview: "Indicadores gerais",
    overviewDescription: "Dados consolidados disponíveis no sistema.",
    activity: "Leitura rápida",
    activityDescription: "Relações calculadas a partir dos indicadores atuais.",
    shortcuts: "Acessos rápidos",
    shortcutsDescription: "Consulte e atualize os principais módulos do SGPPF.",
    viewModule: "Ver módulo",
    recentShare: "Publicações recentes",
    recentShareDescription: "Participação dos últimos 3 anos no total registrado.",
    completedShare: "Orientações concluídas",
    completedShareDescription: "Participação das conclusões no total registrado.",
    noBasis: "Sem base suficiente para calcular",
    publicationsTotal: "Publicações",
    publicationsLast3y: "Publicações (últimos 3 anos)",
    advisingsTotal: "Orientações",
    advisingsCompleted: "Orientações concluídas",
    activeFundedProjects: "Projetos financiados ativos",
    fundsReceived: "Recursos captados (BRL)",
    empty: "Sem dados ainda",
  },
} as const;
