/**
 * Brazilian-Portuguese UI copy. Components reference these keys; no hardcoded
 * pt-BR strings live in components (KTD11). Entity units extend their sections.
 */
export const labels = {
  app: {
    name: "SGPPF",
    full: "Sistema de Gestão de Projetos, Publicações e Financiamentos",
  },
  nav: {
    dashboard: "Painel",
    researchers: "Pesquisadores",
    projects: "Projetos",
    publications: "Publicações",
    advisings: "Orientações",
    admin: "Administração",
    signOut: "Sair",
  },
  roles: {
    admin: "Administrador",
    researcher: "Pesquisador",
    consultant: "Consultor",
  },
  researcher: {
    name: "Nome",
    email: "E-mail",
    position: "Cargo",
    area: "Área de atuação",
    role: "Papel",
    orcid: "ORCID",
    lattes: "Currículo Lattes (URL)",
    scholar: "Google Scholar ID",
    employmentType: "Vínculo",
    affiliationDate: "Data de admissão",
    inactive: "Inativo",
  },
  publication: {
    title: "Título",
    doi: "DOI",
    type: "Tipo",
    year: "Ano",
    venue: "Veículo (periódico/evento)",
    issn: "ISSN",
    url: "URL",
    qualis: "Qualis",
    impactFactor: "Fator de impacto",
    citationCount: "Citações",
    area: "Área de conhecimento",
    authors: "Autores",
    claimAuthorship: "Sou autor(a)",
    corresponding: "correspondente",
    noAuthors: "Nenhum autor vinculado",
    doiPreviewHint: "Confira os dados importados do Crossref antes de salvar.",
    doiExists: "Esta publicação já existe.",
    viewExisting: "Ver publicação",
    doiInvalid: "DOI inválido.",
    doiNotFound: "DOI não encontrado no Crossref.",
    doiFailed: "Falha ao consultar o Crossref. Tente novamente ou insira manualmente.",
    importByDoiTitle: "Importar por DOI",
    manualEntry: "Ou cadastre manualmente",
  },
  publicationTypes: {
    article: "Artigo",
    conference_paper: "Trabalho em congresso",
    book: "Livro",
    book_chapter: "Capítulo de livro",
    technical_report: "Relatório técnico",
    patent: "Patente",
  },
  project: {
    title: "Título",
    code: "Código",
    modality: "Modalidade",
    status: "Situação",
    lead: "Responsável",
    startDate: "Início",
    endDate: "Término",
    funding: "Financiamentos",
  },
  projectStatus: {
    planned: "Planejado",
    in_progress: "Em andamento",
    completed: "Concluído",
    cancelled: "Cancelado",
  },
  funding: {
    agency: "Agência",
    modality: "Modalidade",
    approved: "Valor aprovado",
    received: "Valor recebido",
    pending: "Saldo",
    status: "Situação",
    startDate: "Início",
    endDate: "Término",
    addTitle: "Adicionar financiamento",
  },
  fundingStatus: {
    approved: "Aprovado",
    in_execution: "Em execução",
    completed: "Encerrado",
    cancelled: "Cancelado",
  },
  actions: {
    create: "Novo",
    edit: "Editar",
    delete: "Excluir",
    save: "Salvar",
    cancel: "Cancelar",
    confirm: "Confirmar",
    search: "Buscar",
    exportCsv: "Exportar CSV",
    importDoi: "Importar por DOI",
  },
  table: {
    previous: "Anterior",
    next: "Próxima",
    records: "registros",
    recordsOne: "registro",
  },
  auth: {
    signIn: "Entrar",
    signUp: "Criar conta",
    email: "E-mail institucional",
    password: "Senha",
    fullName: "Nome completo",
    noAccount: "Não tem conta?",
    hasAccount: "Já tem conta?",
    signInWithMicrosoft: "Entrar com Microsoft", // shown once Azure provider is enabled
  },
  errors: {
    required: "Campo obrigatório",
    invalidEmail: "E-mail inválido",
    invalidCredentials: "E-mail ou senha inválidos",
    duplicate: "Esse valor já está em uso",
    notMauaEmail: "Use seu e-mail institucional da Mauá",
    unauthorized: "Você não tem permissão para esta ação",
    generic: "Algo deu errado. Tente novamente.",
  },
  dialogs: {
    confirmDelete: {
      title: "Confirmar exclusão",
      description: "Esta ação não pode ser desfeita.",
      confirm: "Excluir",
      cancel: "Cancelar",
    },
  },
  empty: {
    researchers: {
      title: "Nenhum pesquisador cadastrado",
      description: "Os pesquisadores aparecerão aqui assim que forem adicionados.",
    },
    projects: {
      title: "Nenhum projeto cadastrado",
      description: "Crie um projeto para começar a registrar financiamentos e publicações.",
    },
    publications: {
      title: "Nenhuma publicação registrada",
      description: "Importe por DOI ou registre manualmente.",
    },
    advisings: {
      title: "Nenhuma orientação registrada",
      description: "As orientações aparecerão aqui assim que forem adicionadas.",
    },
    funding: {
      title: "Nenhum financiamento registrado",
      description: "Adicione um contrato de financiamento a este projeto.",
    },
  },
  dashboard: {
    title: "Painel",
    publicationsTotal: "Publicações",
    publicationsLast3y: "Publicações (últimos 3 anos)",
    advisingsTotal: "Orientações",
    advisingsCompleted: "Orientações concluídas",
    activeFundedProjects: "Projetos financiados ativos",
    fundsReceived: "Recursos captados (BRL)",
    empty: "Sem dados ainda",
  },
} as const;
